#!/bin/bash

# 모든 서비스 접속 URL 표시 스크립트

echo "🌐 MSA 예제 환경 - 서비스 접속 URL 목록"
echo "=============================================="

echo ""
echo "📊 Telemetry (모니터링 & 관찰성)"
echo "--------------------------------"
echo "• Rancher (클러스터통합관리): http://localhost:30019 (초기: admin123)"
echo "• Fluent Bit (컨테이너로그): 백그라운드 서비스"
echo "• OpenSearch (로그취합):     http://localhost:30009"
echo "• OpenSearch Dashboard:     http://localhost:30010"
echo "• Prometheus (자원):        http://localhost:30005"
echo "• Grafana (자원시각화):     http://localhost:30007 (admin/admin123)"
echo "• Envoy (네트워크):         http://localhost:30017"
echo "• Istio (데이터수집):       서비스메시"
echo "• Kiali (네트워크시각화):   http://localhost:30004"
echo "• Jaeger (서비스추적):      http://localhost:30008"

echo ""
echo "🔧 CI/CD & 개발 도구"
echo "-------------------"
echo "• Gitea (형상관리):        http://localhost:30011 (admin/admin123)"
echo "• Tekton (프레임워크):     http://localhost:30016"
echo "• Nexus (라이브러리):      http://localhost:30012"
echo "• SonarQube (소스취약점):  http://localhost:30013 (admin/admin)"
echo "• Argo CD (APP자동배포):   http://localhost:30021 (admin/초기비밀번호)"
echo "• Harbor (이미지저장):     http://localhost:30002 (admin/Harbor12345)"
echo "• Trivy (이미지취약점):    http://localhost:30023"

echo ""
echo "🔒 보안 & 운영"
echo "---------------"
echo "• Polaris:              http://localhost:30014"
echo "• MinIO (Velero):       http://localhost:30015 (minio/minio123)"

echo ""
echo "🏗 인프라 관리"
echo "---------------"
echo "• Rancher:              http://localhost:30019 (초기 비밀번호: admin123)"
echo "• Rancher HTTPS:        https://localhost:30020"
echo "• Envoy Proxy:          http://localhost:30017"
echo "• Envoy Admin:          http://localhost:30018"

echo ""
echo "🌍 네트워크 & MSA 서비스"
echo "------------------------"
echo "• Ingress NGINX:        http://localhost:30080"
echo "• MSA Frontend:         http://msa.local (Ingress를 통해)"
echo "• API Gateway:          http://gateway.local/api"
echo "• User API:             http://gateway.local/api/users"
echo "• Order API:            http://gateway.local/api/orders"
echo "• Product API:          http://gateway.local/api/products"

echo ""
echo "📝 참고 사항"
echo "------------"
echo "• 모든 서비스가 준비되는 데 시간이 걸릴 수 있습니다."
echo "• 'kubectl get pods -A' 명령으로 파드 상태를 확인하세요."
echo "• Rancher 접속 시 'rancher.local' 도메인을 사용하려면"
echo "  /etc/hosts에 '127.0.0.1 rancher.local' 추가 필요" 